# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 
  desc "Flutter Doctor"
  lane :flutter_doctor do
    Dir.chdir "../.." do
      sh("flutter", "doctor", "-v")
    end
  end
  
  desc "Get Packages and Clean old Builds"
    lane :clean do
      Dir.chdir "../.." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
      end
  end

  desc "Generate apk Release"
    lane :generate_apk do
      Dir.chdir "../.." do
        sh "flutter build apk --release --build-name=$name --build-number=$number"
      end
  end

  desc "Generate aab Release"
    lane :generate_aab do
      Dir.chdir "../.." do
        sh"flutter build appbundle --release --build-name=$name --build-number=$number"
      end
  end

  #load the app center token from .env file if exists 
  if File.exist?('../.env')
    open('../.env', 'r').readlines.each do |l|
     kv = l.split('=')
     ENV[kv[0]] = kv[1].chomp
    end
   end
 

  desc "Fetch Lastet Version Number in app center"
    lane :fetch_version do
      UI.message("\n\n\n=====================================\n Fetch latest version: \n=====================================")
      version = appcenter_fetch_version_number(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_name: "mayssa.namsi-gmail.com",
        app_name: "artificial-insight-app"
    )
    UI.message(version.to_s)
  end

end
