# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 
  desc "Flutter Doctor"
  lane :flutter_doctor do
    Dir.chdir "../.." do
      sh("flutter", "doctor", "-v")
    end
  end
  
  desc "Get Packages and Clean old Builds"
    lane :clean do
      Dir.chdir "../.." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
      end
  end

  desc "Generate apk Release"
    lane :generate_apk do
      Dir.chdir "../.." do
        sh "flutter build apk --release --build-name=$name --build-number=$number"
      end
  end
  
end
